require 'pathname'
require 'set'
require 'defsdb'
require 'parser/current'

require 'rubber_duck/version'
require 'rubber_duck/application_helper'
require 'rubber_duck/control_flow_analysis'
require 'rubber_duck/query'
require 'rubber_duck/query/trace'
